version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Gradle...
      - chmod +x gradlew

  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build -x test   # Skips all tests

  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir -p output
      - cp build/libs/*.jar output/

artifacts:
  files:
    - output/**/*.jar
